### ISSUE TITLE
bot permission

### ISSUE THREAD

**Issue by hienaman** [MinoMino/minqlbot#8]
i have set up the bot, one on standalone and one on steam btw,,, anyway in either case my bot have permission level 0, obviously with admin or referee status,,any help?

**Comment by MinoMino** [comment]
That's exactly what happens when the "Nickname" field in the config isn't set correctly. If the error isn't obvious, create a [gist](https://gist.github.com/) with the config so I can have a look at it.

**Comment by hienaman** [comment]
basically where it was saying Nickname: YourBotPluginDirectory, i have put in Nickname:hienaman  YourBotPluginDirectory just added myname after Nickname:

**Comment by MinoMino** [comment]
Well, [according to quakelive.com](http://www.quakelive.com/#!profile/summary/hienaman) there is no account called "hienaman". So if you're running the bot on an account, it's not called "hienaman", and thus the bot does not know your account's name. This will lead to the bot thinking whoever is executing commands is just some random guy, not the account the bot itself is running on. As of right now, the bot can't figure out the account name by itself, so it's important the nickname field is correct.

**Comment by hienaman** [comment]
thats absolutely right i have given that as an example, but an issue still persist, funny enough i have also noticed that wherever i go im taking bot with me

**Comment by MinoMino** [comment]
Sorry, but I'm not sure what you're saying. Did you solve the issue? If not, please make a gist of the config so I can have a look at it. I'd also need to know the exact name of the account the bot is running on.

**Comment by hienaman** [comment]
thats a gist
https://gist.github.com/hienaman/dffe593069ed52280458
what i meant before was that i can go into any server and i act as a bot in there even if there is already a bot on a server, but im always permission 0,, on my or on other people servers

**Comment by MinoMino** [comment]
Change line 3:

`Nickname:BaTTleJuice YourBot`

into

`Nickname: BaTTleJuice`

Then restart the bot and it should be fixed.

**Comment by hienaman** [comment]
Thank you very much. You are The Man. Perm level 999 works great, and congratulations on creating the bot its exactly what was missing from quake.

**Comment by MinoMino** [comment]
No problem.
